name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 pi@155.4.68.41 << 'EOF'
            cd /home/pi/SteenBudgetSolution
            echo "Current Git Status:"
            git status
            git pull origin master
            echo "After Git Pull:"
            git log -1
            
            # Correct backend directory and permissions
            if [ -d "Backend" ]; then
              cd Backend
              sudo chmod -R 777 .
              dotnet publish -c Release -o /var/www/backend
              sudo systemctl restart steenbudget
            else
              echo "Backend directory not found!"
            fi

            # Correct frontend directory
            if [ -d "Frontend" ]; then
              cd ../Frontend
              npm install
              npm run build
              sudo cp -r build/* /var/www/html/
              sudo systemctl restart nginx
            else
              echo "Frontend directory not found!"
            fi

            echo "Contents of /var/www/html:"
            ls -l /var/www/html
          EOF
