name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 pi@155.4.68.41 << 'EOF'
            set -e
            cd /home/pi/SteenBudgetSolution
            echo "Current Git Status:"
            git status
            git pull origin master
            echo "After Git Pull:"
            git log -1

            # Fix permissions for backend directory
            sudo chmod -R 777 /var/www/backend

            # Publish and deploy backend
            cd Backend
            dotnet publish -c Release -o /var/www/backend
            sudo systemctl restart steenbudget

            # Build and deploy frontend
            cd ../Frontend
            npm install
            npm run build
            sudo cp -r build/* /var/www/html/
            sudo systemctl restart nginx

            echo "Contents of /var/www/html:"
            ls -l /var/www/html
          EOF
