name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Raspberry Pi
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 pi@155.4.68.41 << 'EOF'
            set -e
            cd /home/pi/SteenBudgetSolution

            # Discard any local changes
            echo "Resetting local changes..."
            git reset --hard
            git clean -fd
            
            echo "Current Git Status:"
            git status
            git pull origin master
            echo "After Git Pull:"
            git log -1
            
            # Ensure necessary directories exist
            sudo mkdir -p /var/www/backend
            sudo mkdir -p /var/www/html
            
            # Fix permissions for backend directory
            sudo chmod -R 777 /var/www/backend
            
            # Publish and deploy backend
            cd Backend
            JWT_SECRET_KEY=${JWT_SECRET_KEY} CONNECTION_STRING=${CONNECTION_STRING} dotnet publish -c Release -o /var/www/backend
            sudo systemctl restart steenbudget
            
            # Check if steenbudget.service needs to be updated
            if ! sudo grep -q "Environment=JWT_SECRET_KEY=" /etc/systemd/system/steenbudget.service; then
              echo "Adding JWT_SECRET_KEY to steenbudget.service"
              echo "Environment=JWT_SECRET_KEY=${JWT_SECRET_KEY}" | sudo tee -a /etc/systemd/system/steenbudget.service
            else
              sudo sed -i "s|Environment=JWT_SECRET_KEY=.*|Environment=JWT_SECRET_KEY=${JWT_SECRET_KEY}|" /etc/systemd/system/steenbudget.service
            fi
            
            if ! sudo grep -q "Environment=CONNECTION_STRING=" /etc/systemd/system/steenbudget.service; then
              echo "Adding CONNECTION_STRING to steenbudget.service"
              echo "Environment=CONNECTION_STRING=${CONNECTION_STRING}" | sudo tee -a /etc/systemd/system/steenbudget.service
            else
              sudo sed -i "s|Environment=CONNECTION_STRING=.*|Environment=CONNECTION_STRING=${CONNECTION_STRING}|" /etc/systemd/system/steenbudget.service
            fi

            sudo systemctl daemon-reload
            sudo systemctl restart steenbudget
            
            # Build and deploy frontend
            cd ../Frontend
            npm install
            npm run build
            
            # Clean the existing content in /var/www/html before copying
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/
            sudo systemctl restart nginx
            
            echo "Contents of /var/www/html:"
            ls -l /var/www/html
          EOF
