name: Verify Environment Variables

on:
  push:
    branches:
      - master

jobs:
  testjob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify Environment Variables
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        run: |
          if [ -z "$JWT_SECRET_KEY" ]; then
            echo "JWT_SECRET_KEY is not set!"
            exit 1
          else
            echo "JWT_SECRET_KEY is set and its length is ${#JWT_SECRET_KEY}"
          fi

          if [ -z "$CONNECTION_STRING" ]; then
            echo "CONNECTION_STRING is not set!"
            exit 1
          else
            echo "CONNECTION_STRING is set and its length is ${#CONNECTION_STRING}"
          fi
