name: Test SSH Key

on: [push]

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        id: ssh-setup
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH key
        run: ssh-add -l

      - name: Debug SSH Key
        run: |
          echo "Private key from secret:"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\n' | head -c 50
          echo "..."
          echo "SSH Agent Keys:"
          ssh-add -l

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection to Raspberry Pi..."
          ssh -v -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -p 2222 pi@155.4.68.41 "echo 'SSH connection successful!'"
