name: Test SSH Key

on: 1

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        id: ssh-setup
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH key
        run: ssh-add -l

      - name: Create SSH Key File
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection to Raspberry Pi..."
          ssh -v -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_rsa -o IdentitiesOnly=yes -p 2222 pi@155.4.68.41 "echo 'SSH connection successful!'"
